version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carteira_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - carteira_network
    depends_on:
      - db

  nginx:
    image: nginx:1.21-alpine
    container_name: carteira_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - carteira_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: carteira_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: carteira
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: carteira_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - carteira_data:/var/lib/mysql
    networks:
      - carteira_network

networks:
  carteira_network:
    driver: bridge

volumes:
  carteira_data:
    driver: local
